services:

  ang:
    build:
      context: angular
    depends_on:
      - backend
    ports:
      - 4200:4200
    expose:
      - "4200"
    volumes:
      - ./angular:/project
      - /project/node_modules
    network_mode: host

  backend:
    build: 
      context: flask
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=5000
    restart: always
    volumes:
      - ./flask:/src
    depends_on:
      - mongo
    network_mode: host

    
  
