services:

  ang:
    build:
      context: angular
    depends_on:
      - backend
    ports:
      - 4200:4200
    expose:
      - "4200"
    volumes:
      - ./angular:/app
      - /app/node_modules

  backend:
    build: 
      context: flask
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9090
    restart: always
    volumes:
      - ./flask:/src
    network_mode: host

    
  
